{% set name = "pyairports" %}
{% set version = "2.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pyairports-{{ version }}.tar.gz
  sha256: 3d60a727fce4da81b9c6393ea8ae0b33d67b37ece344dffc863f749e3ad62bcd

build:
  entry_points:
    - pyairports=pyairports.airports:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}

test:
  imports:
    - pyairports
  commands:
    - pip check
    - pyairports --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/ozeliger/pyairports
  summary: Airport and other locations database
  license: Apache-2.0
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - pavelzw
